import numpy as np
import xarray as xr
import time
from scipy.interpolate import interp1d
import pandas as pd
import warnings
import matplotlib.pyplot as plt
import seaborn as sns
from geodata_v3 import Global_Data
from postprocessor import PostProcessor
from abatement_model import AbatementEstimator
import geopandas as gpd
import rioxarray as rxr
warnings.filterwarnings("ignore")

class LCOEEstimator:
    def __init__(self, data_path, country_grids, electricity_prices, solar_results, wind_results, capex_mapping, generation_data, country_codes, country_mapping, economic_parameters, output_folder, land_cover, land_mapping, GDP, solar_cf, wind_cf, country_waccs_2024, carbon_intensity, IMF_inflation, IMF_currency):
        """ Initialises the LCOE Estimator class, which is used to calculate 1) the LCOE using input WACC values from FinCoRE and 2) the required reductions in the CoC needed to reach national electricity prices
        
       
        Inputs:
        Data_path - path direction to Data inputs
        Country_grids - geospatial coding for national territories
        Electricity_Prices - Country Electricity Prices (consumer retail prices).
        Wind_results - mean wind capacity factors, generated by RENEWABLES NINJA
        Solar_results - mean solar capacity factors, generated by PV Lib
        CAPEX_mapping - Solar and Wind CAPEX costs taken from IRENA Renewable Generation Costs
        Generation_Data - Ember Yearly Generation Data for 2000-2023
        CRP_Data - Data on Country Risk Premiums, taken from Damodaran for multiple years.
        Country_codes - Country coding to ISO 3 codes
        Country_mapping - netcdf file mapping gridcells to country codes
        Economic_Parameters - contains the assumptions and constants used by the model
        Output_folder - Output folder for results printing
        Land_Cover - netcdf file with codings for land cover categories
        Land_mapping - CSV file containing land utilisation rates for land cover categories
        TIAM_Region - Country mapping with TIAM-regions
        Uniform_Factor - value to use for a uniform global WACC analysis
        Country_Waccs_2024 - overide for 2024 WACCS

        
        Classes
        AbatementEstimator Class: Class that generates estimates of lifetime abatement based on current and future grid intensities.
        Geodata: Class to generate geodata on countries, distance to shore etc.
        PostProcessor: Class to perform post processing and create plots for the manuscript.
        """
        # Read in capacity factors
        self.solar_cf = xr.open_dataset(data_path + solar_cf)['CF']
        self.wind_cf = xr.open_dataset(data_path + wind_cf)['CF']

        # Create country mapping with regional details
        self.country_mapping = pd.read_csv(data_path + country_mapping)

        # Read in other inputs
        self.output_folder = output_folder
        self.country_grids = xr.open_dataset(data_path + country_grids)
        self.electricity_prices = pd.read_csv(data_path + electricity_prices)
        self.capex_mapping = pd.read_csv(data_path + capex_mapping)
        self.country_codes = pd.read_csv(data_path + country_codes)
        self.GDP_data = pd.read_csv(data_path + GDP)
        self.carbon_intensity = carbon_intensity
        self.land_cover = xr.open_dataset(data_path + land_cover)
        self.land_mapping = pd.read_csv(data_path + land_mapping)
        self.IMF_inflation = pd.read_csv(data_path + IMF_inflation)
        self.IMF_exchange = pd.read_csv(data_path + IMF_currency)
        self.IMF_exchange = self.get_er_euro()
        self.ember_data = pd.read_csv(data_path + generation_data)
        self.cost_recovery = pd.read_csv(data_path + "Cost_Recovery_Exc_Subsidies.csv")

        # Read in other renewable inputs
        self.hydro_inputs = pd.read_excel(data_path + "Renewable_Inputs.xlsx", sheet_name="HYDRO")
        self.geothermal_inputs = pd.read_excel(data_path + "Renewable_Inputs.xlsx", sheet_name="GEOTHERMAL")
        self.bioenergy_inputs = pd.read_excel(data_path + "Renewable_Inputs.xlsx", sheet_name="BIOENERGY")
        self.ren_mapping = pd.read_excel(data_path + "Renewable_Inputs.xlsx", sheet_name="MAPPING")
        self.geothermal_potential = pd.read_csv(data_path + "Geothermal_allPlacements.csv")
        self.bio_potential = rxr.open_rasterio(data_path +"Biomass_crop_residue_ton.tif")
        
        # Read in costs and assumptions
        self.economic_parameters = pd.read_csv(data_path + economic_parameters)
        self.solar_opex = self.economic_parameters.loc[self.economic_parameters['Parameter'] == "solar_op_cost", "Value"].values[0]
        self.offshore_opex = self.economic_parameters.loc[self.economic_parameters['Parameter'] == "offshore_op_cost", "Value"].values[0]
        self.wind_opex = self.economic_parameters.loc[self.economic_parameters['Parameter'] == "onshore_op_cost", "Value"].values[0]
        self.lifetime = self.economic_parameters.loc[self.economic_parameters['Parameter'] == "lifetime", "Value"].values[0]
        
        # Get renewables capacity, in kWs
        self.renewables_capacity = self.economic_parameters.loc[self.economic_parameters['Parameter'] == "renewables_capacity", "Value"].values[0]
        
        # Include cost of capital
        self.country_wacc_mapping = pd.read_csv(data_path + country_waccs_2024)
        self.country_wacc_mapping = self.fill_country_gaps()

        # Develop default share
        self.default_share = 0.3

        # Set capture rates
        self.solar_capture_rate = 0.6
        self.wind_capture_rate = 0.7
        self.hurdle_rate = (0.06 + 1)/(1+0.02) - 1 # Fischer equation to convert nominal to real rates, assuming 2% inflation
        
        # Read in solar/wind data and process
        self.solar_input = xr.open_dataset(data_path + solar_results)
        self.wind_input = xr.open_dataset(data_path + wind_results)
        self.solar_processed, self.wind_processed = self.process_inputs()
        self.wind_onshore = xr.where(np.isnan(self.solar_processed), np.nan, self.wind_processed)
        self.wind_offshore = xr.where(np.isnan(self.solar_processed), self.wind_processed, np.nan)
        
        # Get geodata class
        self.geodata_class = Global_Data((data_path + "ETOPO_bathymetry.nc"),(data_path+"distance2shore.nc"), (data_path+"country_grids.nc"), self.wind_input)
        self.geodata = self.geodata_class.get_countries_in_required_resolution()
        self.offshore_mask = self.geodata_class.get_offshore_mask() 
        self.wholesale_grids, self.retail_grids = self.calculate_national_prices_v4()
        #self.future_inflation = self.inflation_grids
        self.future_inflation = None

        # Process hydro
        self.GDW_barriers = self.process_hydro_shapefiles(data_path + "GDW_barriers_v1_0.shp", "LAT_RIV", "LONG_RIV")
        self.GDW_reservoirs = self.process_hydro_shapefiles(data_path + "GDW_reservoirs_v1_0.shp", "LAT_RIV", "LONG_RIV")


    def get_er_euro(self):

        euro_iso3 = [
            "AUT", "BEL", "HRV", "CYP", "EST", "FIN", "FRA", "DEU", "GRC", "IRL", "ITA",
            "LVA", "LTU", "LUX", "MLT", "NLD", "PRT", "SVK", "SVN", "ESP"
        ]

        # column names in your dataframe (change as needed)
        country_col = "COUNTRY"
        code_col = "Country code"  # or "Country code"
        year_col = "Year"
        value_col = "Value"  # exchange rate value

        # 1) isolate Euro Area template rows
        er_data = self.IMF_exchange.copy()
        euro_ers = er_data[er_data[country_col].eq("Euro Area (EA)")].copy()

        # 2) duplicate for each euro country
        expanded = []
        for iso in euro_iso3:
            tmp = euro_ers.copy()
            tmp[code_col] = iso
            # Optional: if you want country field changed too
            # tmp[country_col] = iso
            expanded.append(tmp)
        ea_expanded = pd.concat(expanded, ignore_index=True)

        # 3) append to original dataframe
        out = pd.concat([er_data, ea_expanded], ignore_index=True)
        out = out.drop_duplicates(subset=[code_col, year_col], keep="first").reset_index(drop=True)

        return out

    def new_country_grids(self, data_path):

        country_grids = xr.open_dataset(data_path + "countries_gridded_0.1deg_v0.1.nc")
        new_grids = country_grids.to_dataframe()
        merged_df = new_grids["iso"].merge(self.country_codes[["alpha-2", "alpha-3"]], how="left", left_on="iso",
                                     right_on="alpha-2").merge(self.country_mapping[["Country code", "index"]])
        final_df = merged_df[["latitude", "longitude", "index"]].rename(columns={"index": "land"})
        country_ds = final_df.drop_duplicates(subset=["latitude", "longitude"]).set_index(
            ["latitude", "longitude"]).to_xarray()
        country_ds = country_ds.assign_coords({"latitude": country_ds.latitude, "longitude": country_ds.longitude})

        return country_ds

    def process_hydro_shapefiles(self, data_path, lat_col, lon_col):

        # Extract shapefile as geopandas
        gdf = gpd.read_file(data_path).to_crs("EPSG:4326")

        # Extract what is needed
        df = gdf[[lat_col, lon_col, "POWER_MW"]].rename(columns={"POWER_MW":"Capacity_MW", lat_col: "latitude", lon_col:"longitude"})
        grid_ds = self.solar_processed
        grid_lat = grid_ds["latitude"].values
        grid_lon = grid_ds["longitude"].values

        if grid_lon.min() >= 0 and df["longitude"].min() < 0:
            df["longitude"] = (df["longitude"] + 360) % 360

        if not np.allclose(np.diff(grid_lat), np.diff(grid_lat)[0]):
            raise ValueError("Latitude grid is not regular")

        if not np.allclose(np.diff(grid_lon), np.diff(grid_lon)[0]):
            raise ValueError("Longitude grid is not regular")

        dlat = grid_lat[1] - grid_lat[0]
        dlon = grid_lon[1] - grid_lon[0]

        # Convert to nearest grid indices
        lat_idx = np.round((df["latitude"].to_numpy() - grid_lat[0]) / dlat).astype(int)
        lon_idx = np.round((df["longitude"].to_numpy() - grid_lon[0]) / dlon).astype(int)

        valid = (
                (lat_idx >= 0) & (lat_idx < len(grid_lat)) &
                (lon_idx >= 0) & (lon_idx < len(grid_lon))
        )

        lat_idx = lat_idx[valid]
        lon_idx = lon_idx[valid]
        capacity_vals = df["Capacity_MW"].to_numpy()[valid]


        if "GDW_reservoirs_v1_0.shp" in data_path:
            plant_count = np.zeros((len(grid_lat), len(grid_lon)), dtype=int)
            np.add.at(plant_count, (lat_idx, lon_idx), 1)
            plant_capacity_da = xr.DataArray(
                plant_count,
                coords={"latitude": grid_ds["latitude"], "longitude": grid_ds["longitude"]},
                dims=("latitude", "longitude"),
                name="Capacity_MW"
            )
        else:
            plant_count = np.zeros((len(grid_lat), len(grid_lon)), dtype=int)
            np.add.at(plant_count, (lat_idx, lon_idx), 1)
            plant_capacity_da = xr.DataArray(
                plant_count,
                coords={"latitude": grid_ds["latitude"], "longitude": grid_ds["longitude"]},
                dims=("latitude", "longitude"),
                name="Capacity_MW"
            )

        return plant_capacity_da

    def fill_country_gaps(self):

        # Get waccs
        country_waccs = self.country_wacc_mapping

        # Get region information
        country_waccs = country_waccs[["Country code", "index", "solar_pv_wacc", "onshore_wacc", "offshore_wacc", "hydro_wacc", "geothermal_wacc", "bioenergy_wacc"]]
        country_waccs = pd.merge(country_waccs, self.country_mapping[["Country code", "sub-region"]], how="left", on="Country code")


        # Find maximums and extract
        region_max = country_waccs.groupby("sub-region").agg("max").reset_index().add_suffix("_max")

        # Merge back onto original
        country_waccs = pd.merge(country_waccs, region_max.drop(columns=["index_max", "Country code_max"]), how="left", left_on=["sub-region"], right_on="sub-region_max")

        # Fill na
        for col in ["solar_pv_wacc", "onshore_wacc", "offshore_wacc", "hydro_wacc", "geothermal_wacc", "bioenergy_wacc"]:
            country_waccs.loc[country_waccs[col].isnull(), col] = country_waccs[f"{col}_max"]

        return country_waccs
    
    
    
    def calculate_lcoe_shares(self, df):
        
        # Calculate OPEX share
        df["OPEX_LCOE_Uniform"] = df["Calculated_OPEX"] / df["electricity_production"] / (df["Uniform_LCOE"] / 1000) * 100
        df["OPEX_LCOE_Country"] = df["Calculated_OPEX"] / df["electricity_production"] / (df["Calculated_LCOE"] / 1000) * 100
        
        # Calculate CAPEX share
        df["CAPEX_LCOE_Uniform"] = df["Calculated_CAPEX"] / df["electricity_production"] / self.lifetime / (df["Uniform_LCOE"] / 1000) * 100
        df["CAPEX_LCOE_Country"] = df["Calculated_CAPEX"] / df["electricity_production"] / self.lifetime / (df["Calculated_LCOE"] / 1000) * 100
        
        # Calculate Financing Cost share
        df["WACC_LCOE_Uniform"] = 100 - df["OPEX_LCOE_Uniform"] - df["CAPEX_LCOE_Uniform"]
        df["WACC_LCOE_Country"] = 100 - df["OPEX_LCOE_Country"] - df["CAPEX_LCOE_Country"]
        
        return df
    
    
    def get_unfccc_II_average(self):
        
        # Define UNFCCC Annex II countries
        annex_ii_countries = ["AUS",  # Australia
        "AUT",  # Austria
        "BEL",  # Belgium
        "CAN",  # Canada
        "DNK",  # Denmark
        "FIN",  # Finland
        "FRA",  # France
        "DEU",  # Germany
        "GRC",  # Greece
        "ISL",  # Iceland
        "IRL",  # Ireland
        "ITA",  # Italy
        "JPN",  # Japan
        "LUX",  # Luxembourg
        "NLD",  # Netherlands
        "NZL",  # New Zealand
        "NOR",  # Norway
        "PRT",  # Portugal
        "ESP",  # Spain
        "SWE",  # Sweden
        "CHE",  # Switzerland
        "TUR",  # Turkey                     
        "GBR",  # United Kingdom
        "USA"]   # United States of America
        
        # Extract UNFCCC countries from estimated WACCs
        extracted_countries = self.country_wacc_mapping[self.country_wacc_mapping['Country code'].isin(annex_ii_countries)]
        
        # Calculate average for onshore, offshore and solar
        onshore_average = np.nanmean(extracted_countries['onshore_wacc'])
        offshore_average = np.nanmean(extracted_countries['offshore_wacc'])
        solar_average = np.nanmean(extracted_countries['solar_pv_wacc'])
        
        return solar_average, onshore_average, offshore_average
    
    
    def process_inputs(self):
        
        
        # Set up latitudes and longitudes for reindexing
        latitudes= np.arange(-60, 85.5, 0.5)
        longitudes = np.arange(-180, 180.625, 0.625)
       
        
        # Reindex results and country mapping
        solar_results = self.solar_input.reindex({"latitude":latitudes, "longitude":longitudes}, method="nearest")
        wind_results = self.wind_input.reindex({"latitude":latitudes, "longitude":longitudes}, method="nearest")
        country_mapping = self.country_grids.reindex({"latitude":latitudes, "longitude": longitudes}, method="nearest")
        country_mapping['country'] = xr.where(np.isnan(country_mapping['land']), country_mapping['sea'], country_mapping['land'])
        self.land_grids = country_mapping['land']
        self.sea_grids = country_mapping['sea']
        self.country_grids = country_mapping
        
        # Reindex capacity factors
        self.solar_cf = self.solar_cf.reindex({"latitude":latitudes, "longitude":longitudes}, method="nearest")
        self.wind_cf = self.wind_cf.reindex({"latitude":latitudes, "longitude":longitudes}, method="nearest")
        
        # Get rid of results in the ocean
        solar_results = xr.where(np.isnan(country_mapping['land'])==True, np.nan, solar_results)
        
        # Calculate annual electricity production from CFs, in kWh per annum
        solar_results['electricity_production'] = solar_results['CF'] * 8760 * self.renewables_capacity
        wind_results['electricity_production'] = wind_results['CF'] * 8760 * self.renewables_capacity
        
        # Store Size
        solar_results['capacity'] = self.renewables_capacity
        wind_results['capacity'] = self.renewables_capacity
        
        return solar_results, wind_results
    
    def calculate_discount_factor_v1(self, discount_rate):

        # Discount rate needs to be in decimal format
        # Set sum of discount factors initially to 1
        discount_factor = 0 
        
        # Loop along all years
        for i in np.arange(1, self.lifetime + 1, 1):
            discount_factor = discount_factor + 1 * (1 + discount_rate) ** (-1 * i)
            
        return discount_factor
    
    
    def calculate_discount_factor_v3(self, discount_rate):
    
        # Discount rate needs to be in decimal format
        # Create an array for the year indices
        years = np.arange(1, self.lifetime + 1)

        # Add a "year" dimension to the years array
        year_da = xr.DataArray(years, dims=["year"], name="year")

        # Expand discount_rate to have a "year" dimension for broadcasting
        discount_rate_expanded = discount_rate.expand_dims(year=year_da)

        # Calculate discount factors for each year and sum along the "year" dimension
        discount_factors = (1 / (1 + discount_rate_expanded) ** year_da).sum(dim="year")

        return discount_factors

    
    def get_relative_costs(self, data, countries):
    
        geodata = self.geodata['land']
        geodata = geodata.reindex({"latitude":data.latitude, "longitude":data.longitude})
        countries_in_mapping = xr.where(np.isin(geodata, countries), data['Initial_LCOE'], np.nan)
        countries_outside = xr.where(np.isin(geodata, countries), np.nan, data['Initial_LCOE'])

        mean_in = np.nanmean(countries_in_mapping)
        mean_out = np.nanmean(countries_outside)
        increase = mean_out / mean_in
        print(f"Countries not in the mapping are {(increase-1)*100:0.2f}% more expensive") 
    
    
    
    def convert_to_nominal(self, discount_rate, inflation_rate, percentage=None):
        
        # Convert discount rate to correct units
        if np.nanmax(discount_rate) > 1:
            discount_rate = discount_rate / 100

        # Convert inflation rate to required units
        if inflation_rate > 1:
            inflation_rate = inflation_rate / 100

        # Fisher Equation
        nominal_rate = (1 + discount_rate) * (1 + inflation_rate) - 1

        if percentage is not None:
            nominal_rate = nominal_rate * 100
        
        return nominal_rate

    def convert_to_real(self, discount_rate, inflation_rate, percentage=None):

        # Convert discount rate to correct units
        if np.nanmax(discount_rate) > 1:
            discount_rate = discount_rate / 100

        # Convert inflation rate to required units
        if inflation_rate > 1:
            inflation_rate = inflation_rate / 100

        # Fisher Equation
        real_rate = (1 + discount_rate) / (1 + inflation_rate) - 1

        if percentage is not None:
            real_rate = real_rate * 100

        return real_rate
    
    
    def calculate_lcoe_v4(self, data, technology, uniform_factor=None, country_list=None):
        
        def calculate_wacc(electricity_production, technology, index, wacc_lb, wacc_ub, national_wacc=None):
            
            # Extract country grids
            if technology == "Offshore Wind":
                country_grids = self.sea_grids.copy()
            else:
                country_grids = self.land_grids.copy()
            
            # Calculate national WACC if specified
            if national_wacc is not None:
                locational_waccs = xr.where(country_grids == index, national_wacc, np.nan)
                
                return locational_waccs
                
            # Get a subset of electricity_production
            national_electricity_production = xr.where(country_grids == index, electricity_production, np.nan)
            
            # Extract min, mean and max electricity production
            national_min = np.nanmin(national_electricity_production)
            national_max = np.nanmax(national_electricity_production)
            
            # Apply a mapping where max electricity production has the minimum wacc
            locational_waccs = xr.where(country_grids == index, wacc_ub - (national_electricity_production - national_min) / (national_max - national_min) * (wacc_ub - wacc_lb), np.nan)
            
            return locational_waccs
        
        # Set inflation factor to convert from 2024 USD to 2026
        inflation_factor = 1.057 * 1.043

        # Extract country grids
        if technology == "Offshore Wind":
            country_index_mapping = self.sea_grids.copy()
        else:
            country_index_mapping = self.land_grids.copy()
        
        # Check if country list is none - if not then list all country numbers
        if country_list is None:
            countries_examined = np.arange(1, 251, 1)
        else:
            countries_examined = country_list
            
        # Convert uniform value into a decimal
        if uniform_factor is not None:
            uniform_factor = uniform_factor / 100
            
        # Read in country waccs
        country_waccs = self.country_wacc_mapping

        # Read in parameters from the data
        electricity_production = data['electricity_production']
        
         # Extract Country CAPEX values
        if technology == "Onshore Wind":
            capex_costs = self.capex_mapping[['index', 'Wind_CAPEX']]
            capex_costs = capex_costs.rename(columns={"index":"country", "Wind_CAPEX":"CAPEX"})
        elif technology == "Solar":
            capex_costs = self.capex_mapping[['index', 'Solar_CAPEX']]
            capex_costs = capex_costs.rename(columns={"index":"country", "Solar_CAPEX":"CAPEX"})
        elif technology == "Offshore Wind":
            capex_costs = self.capex_mapping[['index', 'Offshore_CAPEX']]
            capex_costs = capex_costs.rename(columns={"index":"country", "Offshore_CAPEX":"CAPEX"})

        
        # Loop over every country
        for index in countries_examined:
            
            if index == 1:
                data['Calculated_LCOE'] = xr.full_like(data['CF'], np.nan)
                data['Hurdle_Rate_LCOE'] = xr.full_like(data['CF'], np.nan)
                data['Undiscounted_LCOE'] = xr.full_like(data['CF'], np.nan)
                data['Calculated_CAPEX'] = xr.full_like(data['CF'], np.nan)
                data['Calculated_OPEX'] = xr.full_like(data['CF'], np.nan)
                data['Estimated_WACC'] = xr.full_like(data['CF'], np.nan)
                data['Estimated_WACC_nom'] = xr.full_like(data['CF'], np.nan)
                data['Future_Inflation'] = xr.full_like(data['CF'], np.nan)
                data['Country'] = xr.full_like(data['CF'], np.nan)
                if uniform_factor is not None:
                    data['Uniform_LCOE'] = xr.full_like(data['CF'], np.nan)

            
            # Calculate total capital costs for the given renewables capacity
            capex = float(capex_costs[capex_costs['country']==index]['CAPEX'].values * self.renewables_capacity * inflation_factor)
            
            # Get WACC values for the country and calculate the OPEX using the CAPEX
            row = country_waccs.loc[country_waccs['index'] == index]
            if technology == "Onshore Wind":
                estimated_wacc = row['onshore_wacc'].values[0]
                self.wind_opex = 0.026
                opex = self.wind_opex * capex # Calculate OPEX as 2.6% of CAPEX annually
            elif technology == "Solar":
                estimated_wacc = row['solar_pv_wacc'].values[0]
                self.solar_opex = 0.023
                opex = self.solar_opex * capex # Calculate OPEX as 2.3% of CAPEX annually
            elif technology == "Offshore Wind":
                estimated_wacc = row['offshore_wacc'].values[0]
                opex = self.offshore_opex * capex # Calculate OPEX as 3% of CAPEX annually

                
            # Convert wacc into a decimal format
            discount_rate = estimated_wacc
            future_inflation = 0


            # Convert to real terms, if needed
            if self.future_inflation is not None:
                discount_rate = self.convert_to_real(discount_rate, future_inflation)


                
            # Calculate discount factor for the given location, using the discount rate
            lb_rate = None
            ub_rate = None
            national_discount_rate = calculate_wacc(electricity_production, technology, index, lb_rate, ub_rate, national_wacc=discount_rate)
            national_discount_factor = self.calculate_discount_factor_v3(national_discount_rate)

            # Do the same for the hurdle rate
            national_discount_rate_hr = calculate_wacc(electricity_production, technology, index, lb_rate, ub_rate,
                                                    national_wacc=discount_rate + self.hurdle_rate)
            national_discount_factor_hr = self.calculate_discount_factor_v3(national_discount_rate_hr)
            
            
            # If the discount rate is NaN, don't calculate the LCOE
            if np.isnan(float(discount_rate)) == True:
                data['Hurdle_Rate_LCOE'] = xr.where(country_index_mapping == index, np.nan, data['Hurdle_Rate_LCOE'])
                data['Calculated_LCOE'] = xr.where(country_index_mapping == index, np.nan, data['Calculated_LCOE'])
                data['Undiscounted_LCOE'] = xr.where(country_index_mapping == index, np.nan, data['Undiscounted_LCOE'])
                if uniform_factor is not None:
                    data['Uniform_LCOE'] = xr.where(country_index_mapping == index, np.nan, data['Uniform_LCOE'])
                

                continue        
            
            # Store the OPEX, CAPEX and WACC values
            data['Calculated_CAPEX'] = xr.where(country_index_mapping == index, capex, data['Calculated_CAPEX'])
            data['Calculated_OPEX'] = xr.where(country_index_mapping == index, opex, data['Calculated_OPEX'])
            data['Estimated_WACC'] = xr.where(country_index_mapping == index, national_discount_rate*100, data['Estimated_WACC']) # Store in % terms, for real if in real terms but nominal otherwise
            data['Country'] = xr.where(country_index_mapping == index, index, data['Country'])

            # Calculate LCOE using the OPEX, CAPEX, DF and Electricity Production
            data['Calculated_LCOE'] = xr.where(country_index_mapping == index, (capex + national_discount_factor * opex) / (national_discount_factor * electricity_production), data['Calculated_LCOE'])
            data['Hurdle_Rate_LCOE'] = xr.where(country_index_mapping == index,
                                               (capex + national_discount_factor_hr * opex) / (
                                                           national_discount_factor_hr * electricity_production),
                                               data['Hurdle_Rate_LCOE'])
            data['Undiscounted_LCOE'] = xr.where(country_index_mapping == index,
                                               (capex + self.lifetime * opex) / (
                                                           self.lifetime * electricity_production),
                                               data['Undiscounted_LCOE'])
            # Store inflation and estimated WACC nom
            # If there is assumed inflation and the calculation is in real terms, store the nominal terms
            if future_inflation is not None:
                data["Estimated_WACC_nom"] = xr.where(country_index_mapping == index, self.convert_to_nominal(data["Estimated_WACC"], future_inflation),
                                                                     data["Estimated_WACC_nom"])
                data["Future_Inflation"] = xr.where(country_index_mapping == index, future_inflation, data["Future_Inflation"])
            
        # Convert LCOE to USD/MWh
        data['Hurdle_Rate_LCOE'] = xr.where(np.isnan(data['Hurdle_Rate_LCOE']), np.nan, data['Hurdle_Rate_LCOE'] * 1000)
        data['Calculated_LCOE'] = xr.where(np.isnan(data['Calculated_LCOE']), np.nan, data['Calculated_LCOE'] * 1000)
        data['Undiscounted_LCOE'] = xr.where(np.isnan(data['Undiscounted_LCOE']), np.nan, data['Undiscounted_LCOE'] * 1000)

        # Add in lifetime data
        data['Lifetime'] = xr.where(np.isnan(data['Calculated_LCOE']), np.nan, self.lifetime)
            
        # Calculate uniform LCOE results
        if uniform_factor is not None:
            
            # Calculate uniform discount factor
            uniform_discount_rate = uniform_factor
            uniform_discount_factor = float(self.calculate_discount_factor_v1(uniform_discount_rate))
            
            # Loop over every country
            for index in countries_examined:
                
                # Calculate total capital costs for a 1 MW plant
                capex = float(capex_costs[capex_costs['country']==index]['CAPEX'].values * self.renewables_capacity)
                
                if technology == "Onshore Wind":
                    opex = self.wind_opex * capex # Calculate OPEX as 2.6% of CAPEX annually
                elif technology == "Solar":
                    opex = self.solar_opex * capex # Calculate OPEX as 2.3% of CAPEX annually
                elif technology == "Offshore Wind":
                    opex = self.offshore_opex * capex # Calculate OPEX as 3% of CAPEX annually

                 # Calculate LCOE
                data['Uniform_LCOE'] = xr.where(country_index_mapping == index, (capex + uniform_discount_factor * opex) / (uniform_discount_factor * electricity_production), data['Uniform_LCOE'])
                
            # Convert LCOE to USD/MWh
            data['Uniform_LCOE'] = xr.where(np.isnan(data['Uniform_LCOE']), np.nan, data['Uniform_LCOE'] * 1000)
            
            # Remove locations with no WACC computed
            data['Uniform_LCOE'] = xr.where(np.isnan(data['Calculated_LCOE']), np.nan, data['Uniform_LCOE']) 
            
        # Remove electricity production in locations with no WACC computed
        data['electricity_production'] = xr.where(np.isnan(data['Calculated_LCOE']), np.nan, data['electricity_production'])

        return data
    
        


    def run_uniform_calculation(self, lcoe_data, wacc, technology):
        
        # Extract LCOE data
        years = lcoe_data.year.values
        zeroth_year = years[0]
        first_year = years[1]
        lcoe = lcoe_data['Calculated_LCOE']
        latitudes = lcoe_data.latitude.values
        longitudes = lcoe_data.longitude.values


        # Calculate old and new discount factors
        discount_factor = self.calculate_discount_factor(wacc)

        # Extract annual costs and electricity production
        annual_electricity_production = lcoe_data['electricity_production'].sel(year=first_year).values
        if technology == "Wind":
            annual_costs = self.wind_op_cost
            capital_costs = self.wind_cost
        elif technology == "Solar":
            annual_costs = self.solar_op_cost
            capital_costs = self.solar_cost

        # Calculate new LCOE based on discount factor
        new_lcoe = xr.where(np.isnan(lcoe)==True, np.nan, (capital_costs + discount_factor * annual_costs ) / (discount_factor * annual_electricity_production))

        # Rename 
        lcoe_data['Uniform_LCOE'] = xr.DataArray(new_lcoe, coords={"latitude":latitudes, "longitude":longitudes})

        return lcoe_data


    def TIAM_cost_supply_curves(self):
        
        # Extract the relevant data
        TIAM_regions = self.TIAM_regions 

        # Specify input
        solar_results = self.solar_lcoe
        onshore_results = self.wind_lcoe
        offshore_results = self.offshore_lcoe

        # Specify uniform factors
        solar_uf = self.solar_pv_uf
        onshore_uf = self.onshore_uf
        offshore_uf = self.offshore_uf

        # Specify postprocessor
        postprocessor = self.postprocessor

        # Call postprocessing function to create the corresponding supply curve
        postprocessor.plot_TIAM_lcoe(solar_results, onshore_results, offshore_results, solar_uf, onshore_uf, offshore_uf)

    def converted_ember_prices(self, cols):

        # Read in ember prices
        eu_prices = pd.read_csv("./DATA/european_wholesale_electricity_price_data_monthly.csv")

        # Convert date to datetime
        eu_prices["Date"] = pd.to_datetime(eu_prices["Date"], errors="coerce")

        # Create year column
        eu_prices["Year"] = eu_prices["Date"].dt.year
        eu_prices["Country code"] = eu_prices["ISO3 Code"]

        # Group and compute yearly mean price
        yearly_avg = (
            eu_prices.groupby(["Country", "Country code", "Year"], as_index=False)["Price (EUR/MWhe)"]
                .mean()
                .rename(columns={"Price (EUR/MWhe)": "avg_price_eur_mwh"})

        )

        # Extract required columns
        yearly_avgs_sel = yearly_avg.loc[yearly_avg["Year"].astype(str).isin(cols)]

        # Merge on exchange rate
        er_long = self.IMF_exchange
        er_long["Exchange_Rate"] = er_long["Value"]

        # Merge back on and convert
        yearly_avgs_sel = yearly_avgs_sel.merge(er_long[["Country code", "Year", "Exchange_Rate"]], how="left", on=["Country code", "Year"])
        yearly_avgs_sel["Electricity_Price"] = yearly_avgs_sel["avg_price_eur_mwh"] / yearly_avgs_sel["Exchange_Rate"]
        yearly_avgs_sel["Price_Type"] = "Wholesale_EB"

        # Extract required columns
        final_prices = yearly_avgs_sel[["Country code", "Year", "Electricity_Price", "Price_Type"]]

        return final_prices

    def converted_cs_prices(self, cols):

        # Read in ember prices
        cs_prices = pd.read_csv("./DATA/climatescope_electricity_prices_2019_2024_yrly.csv").rename(columns={"year":"Year", "price":"Electricity_Price"})

        # Convert into a long format
        wholesale_prices = cs_prices[cs_prices["segment"]=="Wholesale"][["Country code", "Year", "Electricity_Price"]]
        wholesale_prices["Price_Type"] = "Wholesale_CS"

        # Convert retail prices into a long format
        retail_prices = cs_prices[cs_prices["segment"] == "Residential"][["Country code", "Year", "Electricity_Price"]]
        retail_prices["Price_Type"] = "Retail_CS"

        # Merge into one
        final_prices = pd.concat([retail_prices, wholesale_prices], ignore_index=True)

        return final_prices

    def calculate_national_prices_v4(self, costrecovery=None):


        # Select columns required
        cols = ["2019", "2020", "2021", "2022", "2023", "2024", "2025"]

        # Extract electricity prices from World Bank
        wbg_electricity_prices = self.electricity_prices
        wbg_electricity_prices["Price_Type"] = "Retail_WBG"
        wbg_electricity_prices["Year"] = 2019
        wbg_electricity_prices["Electricity_Price"] = wbg_electricity_prices["Electricity_Price"] * 10 # Converting from c/kWh to USD/MWh
        electricity_prices = wbg_electricity_prices[["Country Name", "Country code", "Year", "Electricity_Price", "Price_Type"]]

        # Extract electricity prices from climate scope
        cs_prices = self.converted_cs_prices(cols)

        # Extract wholesale electricity prices
        wholesale_prices = self.converted_ember_prices(cols)

        # Create list of full countries and then fill in missing countries with regional benchmarks
        electricity_prices_collated = pd.concat([electricity_prices, cs_prices, wholesale_prices], ignore_index=True)

        # Extract long files for inflation and exchange rates
        er_long = self.IMF_exchange.rename(columns={"value":"Exchange_Rate"})
        ir_data = self.IMF_inflation
        er_values_final = er_long.loc[er_long["Year"]==int(cols[-1])].rename(columns={"Value":"Exchange_Rate_Final"})[["Country code", "Exchange_Rate_Final"]]

        # Create cumulative inflation array
        ir_data = ir_data[["Country code"] + cols].copy()
        year_cols = [c for c in ir_data.columns if c != "Country code"]
        factors = 1 + ir_data[year_cols] / 100.0
        cum_factors = factors.iloc[:, ::-1].cumprod(axis=1).iloc[:, ::-1]
        ir_long = pd.concat([ir_data[["Country code"]], cum_factors], axis=1).melt(
            id_vars="Country code",
            var_name="Year",
            value_name="Cumulative_Inflation"
        )
        ir_long["Year"] = ir_long["Year"].astype(int)


        # Add in data
        electricity_prices_er = electricity_prices_collated.merge(er_long[["Country code", "Year", "Exchange_Rate"]],
                                                                        how="left", on=["Country code", "Year"])
        electricity_prices_full = electricity_prices_er.merge(ir_long, how="left", on=["Country code", "Year"])
        electricity_prices_full = electricity_prices_full.merge(er_values_final, how="left", on=["Country code"])

        # Apply local currency inflation and exchange rates to convert to final USD terms
        electricity_prices_full["Local_Electricity_Price_Nom"] = electricity_prices_full["Electricity_Price"] * electricity_prices_full["Exchange_Rate"]
        electricity_prices_full["Local_Electricity_Price_Real"] = electricity_prices_full["Local_Electricity_Price_Nom"] * electricity_prices_full["Cumulative_Inflation"]
        electricity_prices_full["Electricity_Price_Real"] = electricity_prices_full["Local_Electricity_Price_Real"] / electricity_prices_full["Exchange_Rate_Final"]

        # Pivot and calculate average across columns
        electricity_prices_pivoted = pd.pivot(electricity_prices_full, index=["Country code", "Price_Type"], columns="Year", values="Electricity_Price_Real").reset_index()
        electricity_prices_pivoted.columns = electricity_prices_pivoted.columns.astype(str)
        electricity_prices_pivoted["Electricity_Price_Avg"] = electricity_prices_pivoted[cols].mean(axis=1, skipna=True)

        # Merge onto the country mapping
        electricity_prices_full = self.country_mapping.merge(electricity_prices_pivoted[["Country code", "Price_Type", "Electricity_Price_Avg"]],
                                                             how="left")
        electricity_prices_full["Price_Type"].fillna("Missing", inplace=True)
        electricity_prices_full = pd.pivot(electricity_prices_full, index=["Country code", "index", "Region", "region", "sub-region", "status"],
                                              columns="Price_Type", values="Electricity_Price_Avg").reset_index()
        electricity_prices_full["Wholesale"] = electricity_prices_full["Wholesale_CS"].fillna(electricity_prices_full["Wholesale_EB"])
        electricity_prices_full["CS_Ratio"] = electricity_prices_full["Wholesale_CS"] / electricity_prices_full[
            "Retail_CS"]
        electricity_prices_full["WBG_Ratio"] = electricity_prices_full["Wholesale_EB"] / electricity_prices_full[
            "Retail_WBG"]
        emde_median_ratio = np.nanmedian(electricity_prices_full["CS_Ratio"])
        wbg_median_ratio = np.nanmedian(electricity_prices_full["WBG_Ratio"])
        overall_mean = np.nanmean([electricity_prices_full["WBG_Ratio"], electricity_prices_full["CS_Ratio"]])

        # Compute regional means and create final retail prices
        wbg_median = electricity_prices_full[["sub-region",
                                              "Retail_WBG"]].groupby("sub-region").agg({"Retail_WBG":
                                               "mean"}).reset_index().rename(columns={"Retail_WBG":"WBG_Regional_Mean"})
        electricity_prices_full = electricity_prices_full.merge(wbg_median, how="left", on="sub-region")
        electricity_prices_full["Retail_WBG"].fillna(electricity_prices_full["WBG_Regional_Mean"], inplace=True)
        electricity_prices_full["Retail_Price_Final"] = electricity_prices_full["Retail_CS"].fillna(
            electricity_prices_full["Retail_WBG"])

        # Calculate cost recovery levels for EMDES
        cost_recovery = self.cost_recovery.copy()
        year_cols = [c for c in cost_recovery.columns if c in cols]
        cost_recovery = cost_recovery[["Country code"] + year_cols]
        cost_recovery["Cost_Recovery_Gap"] = 1 - cost_recovery[year_cols].mean(axis=1, skipna=True).clip(upper=100) /100
        cost_recovery.to_csv("costrecovery.csv")
        cost_recovery_gap = cost_recovery[["Country code", "Cost_Recovery_Gap"]].groupby("Country code").agg("mean").reset_index()
        electricity_prices_full = electricity_prices_full.merge(cost_recovery_gap, how="left", on="Country code")
        electricity_prices_full["Cost_Recovery_Gap"] = electricity_prices_full["Cost_Recovery_Gap"].fillna(0)

        # Calculate the wholesale electricity price to use by country
        electricity_prices_full["Wholesale_Price_Final"] = electricity_prices_full["Wholesale"]
        electricity_prices_full.loc[(electricity_prices_full["status"]=="EMDE") &
                                    (electricity_prices_full["Wholesale"].isnull()),
                                    "Wholesale_Price_Final"] = emde_median_ratio * electricity_prices_full["Retail_Price_Final"] * (1 - electricity_prices_full["Cost_Recovery_Gap"])
        electricity_prices_full.loc[(electricity_prices_full["status"] == "Advanced") &
                                    (electricity_prices_full["Wholesale"].isnull()),
                                    "Wholesale_Price_Final"] = wbg_median_ratio * electricity_prices_full["Retail_Price_Final"]

        # Save the output file
        electricity_prices_full.to_csv(self.output_folder + "Electricity_Price_Assumptions.csv")


        # Apply onto the country grids
        price_grids = self.country_grids["country"]
        mapping = dict(zip(electricity_prices_full["index"], electricity_prices_full["Wholesale_Price_Final"]))
        wholesale_price_grids = xr.apply_ufunc(
            np.vectorize(lambda x: mapping.get(x, x)),
            price_grids
        )

        adjusted_mapping = dict(zip(electricity_prices_full["index"], electricity_prices_full["Retail_Price_Final"]))
        retail_price_grids = xr.apply_ufunc(
            np.vectorize(lambda x: adjusted_mapping.get(x, x)),
            price_grids
        )


        return wholesale_price_grids, retail_price_grids


    def calculate_required_waccs_v2(self, data, lcoe=None, benchmark=None, allow_negative_irr=True, technology=None):

        def _npv_rate(r, capex0, cfa, n):
            # domain guard
            if r <= -1.0:
                return np.nan
            if np.isclose(r, 0.0):
                return -capex0 + cfa * n
            return -capex0 + cfa * (1.0 - (1.0 + r) ** (-n)) / r

        def _solve_irr_scalar(capex0, cfa, n):
            # Guardrails
            if np.isnan(capex0) or np.isnan(cfa) or np.isnan(n) or capex0 <= 0 or n <= 0:
                return np.nan

            n = int(round(n))

            # choose bracket
            lo = -0.99 if allow_negative_irr else 0.0
            hi = 2.0  # 200%

            f_lo = _npv_rate(lo, capex0, cfa, n)
            f_hi = _npv_rate(hi, capex0, cfa, n)

            if np.isnan(f_lo) or np.isnan(f_hi):
                return np.nan
            if f_lo == 0:
                return lo
            if f_hi == 0:
                return hi

            # no root in bracket
            if f_lo * f_hi > 0:
                if allow_negative_irr and f_lo < 0 and f_hi < 0:
                    return -1.0  # -100% IRR
                return np.nan

            # bisection
            for _ in range(100):
                mid = 0.5 * (lo + hi)
                f_mid = _npv_rate(mid, capex0, cfa, n)

                if np.isnan(f_mid):
                    return np.nan
                if np.isclose(f_mid, 0.0, atol=1e-12):
                    return mid

                if f_lo * f_mid < 0:
                    hi = mid
                    f_hi = f_mid
                else:
                    lo = mid
                    f_lo = f_mid

            return 0.5 * (lo + hi)

        # -------------------------
        # Preprocessing & constants
        # -------------------------
        data = data.drop_vars('Required_WACC', errors="ignore")

        latitudes = data.latitude.values
        longitudes = data.longitude.values

        annual_electricity_production = data['electricity_production']  # kWh for 1 MW
        initial_lcoe = data['Calculated_LCOE']  # USD/MWh for 1 MW

        annual_costs = data['Calculated_OPEX']  # USD/MW/year
        capital_costs = data['Calculated_CAPEX']  # USD for 1 MW

        # discount factor based on estimated WACC
        discount_factor = self.calculate_discount_factor_v1(data["Estimated_WACC"] / 100 + self.hurdle_rate)

        current_wacc = data["Estimated_WACC"] + self.hurdle_rate
        N = int(self.lifetime)

        # Calculate capture rate
        if technology == "Solar":
            capture_rate = self.solar_capture_rate
        elif technology=="Wind":
            capture_rate = self.wind_capture_rate
        else:
            capture_rate = 1

        # Normalize benchmark into a list of values to loop over
        if benchmark is None:
            benchmark_list = [None]
        elif np.isscalar(benchmark):
            benchmark_list = benchmark
            benchmark_list = [None] + benchmark_list
        else:
            # assume iterable of numbers
            benchmark_list = list(benchmark)
            benchmark_list = [None] + benchmark_list

        for bm in benchmark_list:
            # Construct a suffix for variable names
            if bm is None:
                suffix = ""
            else:
                suffix = f"{bm}"

            # -------------------------
            # Determine LCOE benchmark
            if bm is None:
                # wholesale-based benchmark
                lcoe_benchmark = self.wholesale_grids / 1000.0 * capture_rate # USD/kWh
            else:
                # retail-based benchmark
                benchmark_ratio = bm / 100.0
                lcoe_benchmark = self.retail_grids * benchmark_ratio * capture_rate / 1000.0  # USD/kWh

            # Store benchmark retail price
            data['Benchmark_Price'+ suffix] = self.retail_grids

            # -------------------------
            # Determine LCOE used
            # -------------------------
            if lcoe is None:
                lcoe_used = lcoe_benchmark
            else:
                # user-provided LCOE (assumed in USD/MWh) -> convert to USD/kWh
                lcoe_used = lcoe / 1000.0
            data['Benchmark_LCOE' + suffix] = lcoe_used

            # -------------------------
            # Benchmark ratio
            # -------------------------
            data['Benchmark_Ratio' + suffix] = data["Hurdle_Rate_LCOE"] / lcoe_used

            # -------------------------
            # Grant equivalent & WACC
            # -------------------------
            # Ensure denominator positive and LCOE above benchmark
            valid_mask = (
                                 (annual_electricity_production * lcoe_used - annual_costs) > 0
                         ) * (data["Hurdle_Rate_LCOE"] > lcoe_used)

            numerator = (
                    capital_costs
                    + annual_costs * discount_factor
                    - lcoe_used * annual_electricity_production * discount_factor
            )

            grant_equivalent = xr.where(
                np.isnan(lcoe_used) | ~valid_mask,
                np.nan,
                (numerator / capital_costs)
            )

            data['Grant_Equivalent_%' + suffix] = grant_equivalent
            data['Grant_Equivalent' + suffix] = grant_equivalent * data['Calculated_CAPEX']

            # Convert grant equivalence to CoC implications in nominal terms
            estimated_waccs = (data["Estimated_WACC"] + self.hurdle_rate) * (1 - data['Grant_Equivalent_%' + suffix])
            estimated_waccs = xr.where(
                np.isnan(lcoe_used) | ~valid_mask,
                np.nan,
                estimated_waccs
            )
            wacc_da = xr.DataArray(
                estimated_waccs,
                coords={"latitude": latitudes, "longitude": longitudes},
            )
            data['Benchmark_WACC' + suffix] = xr.where(
                np.isnan(initial_lcoe),
                np.nan,
                wacc_da
            )

            # WACC reductions
            data["WACC_Reductions" + suffix] = current_wacc - data["Benchmark_WACC" + suffix]
            data["WACC_Reductions" + suffix] = xr.where(
                data["WACC_Reductions" + suffix] < 0,
                -111,
                data["WACC_Reductions" + suffix],
            )

            # -------------------------
            # IRR at benchmark price
            benchmark_price_usd_per_kwh = lcoe_used
            annual_revenue = annual_electricity_production * benchmark_price_usd_per_kwh
            annual_costs_for_irr = annual_costs
            annual_cashflow = annual_revenue - annual_costs_for_irr

            irr_decimal = xr.apply_ufunc(
                np.vectorize(_solve_irr_scalar),
                capital_costs,
                annual_cashflow,
                kwargs={"n": N},
                vectorize=True,
                dask="parallelized",
                output_dtypes=[float],
            )

            data["Benchmark_IRR" + suffix] = xr.where(
                np.isnan(initial_lcoe) | np.isnan(lcoe_used),
                np.nan,
                irr_decimal * 100.0  # %
            )

            data["Benchmark_IRR" + suffix] = xr.where(
                ~np.isnan(initial_lcoe) & np.isnan(irr_decimal),
                -99,
                data["Benchmark_IRR" + suffix]
            )



        return data

    
    def calculate_abatement_costs(self, data, lcoe=None, benchmark=None, technology=None):
        
        # Call the required WACC function
        data = self.calculate_required_waccs_v2(data, lcoe, benchmark)
        
        # Calculate grant equivalent
        data = self.calculate_grant_abatement(data, benchmark)
        
        return data
    

    def calculate_grant_abatement(self, data, benchmark=None):

        if benchmark is None:
            benchmark_list = [""]
        else:
            benchmark_list = benchmark
        benchmark_list = [None] + benchmark_list
        for benchmark in benchmark_list:
            if benchmark is not None:
                suffix = str(benchmark)
            else:
                suffix = ""
            data["Grant_Equivalent" + suffix] = xr.where(data["Grant_Equivalent" + suffix] < 0, -111,
                                                        data["Grant_Equivalent" + suffix])

            # Calculate the percentage grant required
            data["Grant_Equivalent_%" + suffix] = xr.where(data["Grant_Equivalent" + suffix] == -111, -111,
                                                              data["Grant_Equivalent_%" + suffix])

            # Calculate the abatement costs in USD per tCO2
            for additionality in ["", "_AF"]:
                data["abatement_cost" + suffix + additionality] = xr.where(data["Grant_Equivalent" + suffix] == -111, -111,
                                                              data["Grant_Equivalent" + suffix] / data["abatement_MW"+ additionality])
                valid = np.isfinite(data["abatement_cost" + suffix + additionality]) & (data["abatement_cost" + suffix + additionality] > 0)
                data["abatement_cost" + suffix + additionality] = xr.where(valid, data["abatement_cost" + suffix + additionality], np.nan)


                # Calculate abatements costs using CI in USD per tCO2
                data["abatement_cost_CI" + suffix + additionality] = xr.where(data["Grant_Equivalent" + suffix] == -111, -111,
                                                                     data["Grant_Equivalent" + suffix] / data[
                                                                         "abatement_CI" + additionality])
                valid = np.isfinite(data["abatement_cost_CI" + suffix + additionality]) & (data["abatement_cost_CI" + suffix + additionality] > 0)
                data["abatement_cost_CI" + suffix + additionality] = xr.where(valid, data["abatement_cost_CI" + suffix + additionality], np.nan)

        return data

    def calculate_lcoe(self, df: pd.DataFrame,
                       r_col: str,
                       lifetime_col: str = "Lifetime",
                       capex_col: str = "CAPEX",
                       om_pct_col: str = "O&M",
                       cf_col: str = "CF") -> pd.Series:
        """
        Calculate LCOE for each row when annual O&M is a fraction of CAPEX.

        Parameters
        ----------
        df : pd.DataFrame
            Must contain CAPEX, annual O&M percentage, capacity factor, and cost of capital.
        lifetime : str
            Column for project lifetime in years.
        capex_col : str
            Column for CAPEX (e.g., $/kW).
        om_pct_col : str
            Column for annual O&M as fraction of CAPEX (e.g., 0.03 for 3%/year).
        cf_col : str
            Column for capacity factor (0-1).
        r_col : str
            Column for cost of capital as fraction (e.g., 0.08 for 8%).

        Returns
        -------
        pd.Series
            LCOE per row (same index as df), in $/kWh if CAPEX is $/kW.
        """

        if df[lifetime_col].min() <= 0:
            raise ValueError("lifetime must be a positive integer")

        required = [capex_col, om_pct_col, cf_col, r_col, lifetime_col]
        missing = [c for c in required if c not in df.columns]
        if missing:
            raise KeyError(f"Missing required columns: {missing}")

        capex = pd.to_numeric(df[capex_col], errors="coerce")
        om_pct = pd.to_numeric(df[om_pct_col], errors="coerce")
        cf = pd.to_numeric(df[cf_col], errors="coerce")
        r = pd.to_numeric(df[r_col], errors="coerce")
        lifetime = pd.to_numeric(df[lifetime_col], errors="coerce")

        # Checks
        if capex.isna().any() or om_pct.isna().any() or cf.isna().any() or r.isna().any():
            raise ValueError("One or more required values are non-numeric or missing")
        if (cf <= 0).any() or (cf > 1).any():
            raise ValueError("capacity_factor must be in (0, 1]")
        if (r < 0).any():
            raise ValueError("cost_of_capital must be >= 0")
        if (om_pct < 0).any():
            raise ValueError("annual_om_pct must be >= 0")

        # CRF (special case r = 0)
        inflation_factor = 1.057 * 1.043
        crf = np.where(
            r == 0,
            1 / lifetime,
            (r * (1 + r) ** lifetime) / ((1 + r) ** lifetime - 1)
        )
        crf_hr = np.where(
            r == 0,
            1 / lifetime,
            ((r + self.hurdle_rate) * (1 + r + self.hurdle_rate) ** lifetime) / ((1 + r + self.hurdle_rate) ** lifetime - 1)
        )

        annual_production = (8760 * cf)
        if r_col == "bioenergy_wacc":
            annual_om = capex * om_pct * inflation_factor + annual_production * 0.004 * inflation_factor
        else:
            annual_om = capex * om_pct * inflation_factor
        if r_col == "geothermal_wacc":
            capex = capex

        lcoe = (capex * crf * inflation_factor + annual_om) / annual_production
        lcoe_hr = (capex * crf_hr * inflation_factor + annual_om) / annual_production
        nodiscount_lcoe = (capex * 1 / lifetime * inflation_factor + annual_om) / annual_production

        # Add to the dataframe (for 1 MW - here we multiply by 1000 to get $/MWh and to get electricity production in kWh)
        df["Calculated_LCOE"] = lcoe * 1000
        df["Hurdle_Rate_LCOE"] = lcoe_hr * 1000
        df["Undiscounted_LCOE"] = nodiscount_lcoe * 1000
        df["electricity_production"] = annual_production * 1000
        df["technical_potential"] = annual_production * 1000
        df["Calculated_CAPEX"] = capex * inflation_factor * 1000
        df["Calculated_OPEX"] = annual_om * 1000
        df["Estimated_WACC"] = r * 100
        df["CF"] = cf
        df["Lifetime"] = lifetime

        # Merge onto country dataset mapping
        country_grids = self.country_grids.rename({"land": "index"})
        country_df = country_grids.to_dataframe().reset_index()
        country_df = country_df.merge(df[["Country", "index", "Calculated_LCOE", "Hurdle_Rate_LCOE", "electricity_production", "Calculated_CAPEX", "Calculated_OPEX", "CF", "Lifetime", "Estimated_WACC", "technical_potential"]], how="left", on="index")
        country_ds = country_df.drop_duplicates(subset=["latitude", "longitude"]).set_index(
            ["latitude", "longitude"]).to_xarray()
        country_ds = country_ds.assign_coords({"latitude": country_ds.latitude, "longitude": country_ds.longitude})

        if r_col == "geothermal_wacc":
            country_ds = self.geothermal_distribution(country_ds)
            country_ds["technical_potential"] = country_ds["Capacity_MW"] * country_ds["CF"] * 8760 * 1e+03
            country_ds.drop_vars("Capacity_MW")
        elif r_col == "bioenergy_wacc":
            country_ds = self.bioenergy_distribution(country_ds)
            country_ds["technical_potential"] = country_ds["Capacity_MW"] * country_ds["CF"] * 8760 * 1e+03
            country_ds.drop_vars("Capacity_MW")
        elif r_col == "hydro_wacc":
            country_ds = self.hydropower_distribution(country_ds)
            country_ds["technical_potential"] = country_ds["Capacity_MW"] * country_ds["CF"] * 8760 * 1e+03
            country_ds.drop_vars("Capacity_MW")

        return country_ds

    def hydropower_distribution(self, country_ds):

        # Extract hydropower data
        hydro_reservoirs = self.GDW_reservoirs
        hydro_dams = self.GDW_barriers

        # Extract hydropower data
        hydro_res_capacity = hydro_reservoirs.fillna(0)
        hydro_dam_capacity = hydro_dams.fillna(0)

        # Create a unified dataframe
        hydro_unified = hydro_res_capacity + hydro_dam_capacity
        country_ds["Capacity_MW"] = hydro_unified

        cutoff = hydro_unified.mean()
        country_ds["Calculated_LCOE"] = country_ds["Calculated_LCOE"].where(country_ds["Capacity_MW"] > cutoff)
        country_ds["electricity_production"] = country_ds["electricity_production"].where(
            country_ds["Capacity_MW"] > cutoff)
        country_ds["technical_potential"] = 0

        return country_ds

    def bioenergy_distribution(self, country_ds):

        # Get bioenergy distribution
        bioenergy_potential = self.bio_potential
        bioenergy_potential = bioenergy_potential.squeeze("band", drop=True).to_dataset(name="potential").rename({"x": "longitude", "y": "latitude"})

        # Get grid lats
        target_lat = country_ds["latitude"].values
        target_lon = country_ds["longitude"].values

        # Use nearest-index approach
        lat_edges = np.concatenate([
            [target_lat[0] - (target_lat[1] - target_lat[0]) / 2],
            (target_lat[:-1] + target_lat[1:]) / 2,
            [target_lat[-1] + (target_lat[-1] - target_lat[-2]) / 2]
        ])
        lon_edges = np.concatenate([
            [target_lon[0] - (target_lon[1] - target_lon[0]) / 2],
            (target_lon[:-1] + target_lon[1:]) / 2,
            [target_lon[-1] + (target_lon[-1] - target_lon[-2]) / 2]
        ])
        bio_binned = (
            bioenergy_potential.groupby_bins("latitude", lat_edges, labels=target_lat).sum(dim="latitude").groupby_bins("longitude", lon_edges,labels=target_lon).sum(dim="longitude")
        )

        # Rename and assign coordinates
        bio_binned = bio_binned.rename({
            "latitude_bins": "latitude",
            "longitude_bins": "longitude"
        })
        bio_binned = bio_binned.assign_coords(
            latitude=target_lat,
            longitude=target_lon
        )

        # Back to DataArray
        cutoff = 19000
        country_ds["Capacity_MW"] = bio_binned["potential"]
        country_ds["Calculated_LCOE"] = country_ds["Calculated_LCOE"].where(country_ds["Capacity_MW"] > cutoff)
        country_ds["electricity_production"] = country_ds["electricity_production"].where(
            country_ds["Capacity_MW"] > cutoff)
        country_ds["technical_potential"] = 0

        return country_ds

    def geothermal_distribution(self, country_ds):

        # Extract geothermal distribution
        geothermal_data = self.geothermal_potential[["lon", "lat", "Pout_Gringarten_MW"]].rename(columns={"lon":"longitude", "lat":"latitude", "Pout_Gringarten_MW":"Capacity_MW"})

        # Get grid latitude and longitudes
        grid_lat = country_ds['latitude'].values
        grid_lon = country_ds['longitude'].values
        dlat = grid_lat[1] - grid_lat[0]
        dlon = grid_lon[1] - grid_lon[0]

        # Get plant locations from dataframe and get closest locations
        plant_lat = geothermal_data['latitude'].values
        plant_lon = geothermal_data['longitude'].values
        plant_capacity = geothermal_data["Capacity_MW"].values
        lat_idx = np.round((plant_lat - grid_lat[0]) / dlat).astype(int)
        lon_idx = np.round((plant_lon - grid_lon[0]) / dlon).astype(int)


        valid = (
                (lat_idx >= 0) & (lat_idx < len(grid_lat)) &
                (lon_idx >= 0) & (lon_idx < len(grid_lon))
        )
        lat_idx = lat_idx[valid]
        lon_idx = lon_idx[valid]
        plant_capacity = plant_capacity[valid]

        # Build empty mask and mark cells that contain at least one plant
        capacity_sum = np.zeros((len(grid_lat), len(grid_lon)), dtype=float)
        np.add.at(capacity_sum, (lat_idx, lon_idx), plant_capacity)

        # Apply onto the original dataframe and fix for locations with no data
        cutoff = 50
        country_ds["Capacity_MW"] = xr.DataArray(
            capacity_sum,
            coords={"latitude": country_ds["latitude"], "longitude": country_ds["longitude"]},
            dims=("latitude","longitude")
        )
        country_ds["Calculated_LCOE"] = country_ds["Calculated_LCOE"].where(country_ds["Capacity_MW"] > cutoff)
        country_ds["electricity_production"] = country_ds["electricity_production"].where(country_ds["Capacity_MW"] > cutoff)
        country_ds["technical_potential"] = 0


        return country_ds



    def calculate_other_renewables(self):

        # Extract the input files for renewables
        country_mapping = self.ren_mapping.copy()
        hydro_results = country_mapping[["index", "Country", "Region"]].merge(self.hydro_inputs, how="left",
                                                                              on="Region").merge(self.country_wacc_mapping[["index", "hydro_wacc"]], how="left", on="index")
        hydro_results = hydro_results.fillna(hydro_results.loc[hydro_results["Region"]=="Other"].iloc[0])
        geothermal_results = country_mapping[["index", "Country", "Region"]].merge(self.geothermal_inputs, how="left",
                                                                              on="Region").merge(self.country_wacc_mapping[["index", "geothermal_wacc"]], how="left", on="index")
        geothermal_results = geothermal_results .fillna(geothermal_results .loc[geothermal_results ["Region"] == "Other"].iloc[0])
        bioenergy_results = country_mapping[["index", "Country", "Region"]].merge(self.bioenergy_inputs, how="left",
                                                                              on="Region").merge(self.country_wacc_mapping[["index", "bioenergy_wacc"]], how="left", on="index")
        bioenergy_results = bioenergy_results.fillna(
            bioenergy_results.loc[bioenergy_results["Region"] == "Other"].iloc[0])

        # Call
        hydro_results = self.calculate_lcoe(hydro_results, r_col="hydro_wacc")
        geothermal_results = self.calculate_lcoe(geothermal_results, r_col="geothermal_wacc")
        bioenergy_results = self.calculate_lcoe(bioenergy_results, r_col="bioenergy_wacc")

        return hydro_results, geothermal_results, bioenergy_results


    def calculate_cheapest_technology_v2(self):

        def calculate_shares(ds, variable):
            s = pd.Series(ds[variable].values.ravel())
            shares = s.value_counts(dropna=True) / s.value_counts(dropna=True).sum()
            for value, frac in shares.items():
                print(f"value: {value}, share: {frac:.4f}")

        datasets = [
            self.solar_lcoe,
            self.wind_lcoe,
            self.hydro_lcoe,
            self.bioenergy_lcoe,
            self.geothermal_lcoe,
        ]
        names = ["Solar", "Onshore Wind", "Hydroelectric", "Bioenergy", "Geothermal"]

        # 1) Make sure all datasets are aligned on same coords/dims
        aligned = xr.align(*datasets, join="outer")

        # 2) Stack full datasets (all variables), not just selected DataArrays
        ds_stack = xr.concat(
            aligned,
            dim=xr.DataArray(names, dims="scenario", name="scenario")
        )

        # 3) Compute cheapest technology from LCOE
        lcoe = ds_stack["Calculated_LCOE"]
        all_nan = lcoe.isnull().all(dim="scenario")
        argmin_idx = lcoe.fillna(float("inf")).argmin(dim="scenario")
        lowest_lcoe = lcoe.min(dim="scenario", skipna=True).rename("Calculated_LCOE")

        # 4) Select all variables at cheapest scenario
        #    This applies argmin_idx pointwise across all dims.
        best = ds_stack.isel(scenario=argmin_idx)

        # 5) Mask cells where all technologies were NaN for LCOE
        best = best.where(~all_nan)

        # 6) Add cheapest technology label + force LCOE to true min
        best["Cheapest_Technology"] = ds_stack["scenario"].isel(scenario=argmin_idx).where(~all_nan)
        best["Calculated_LCOE"] = lowest_lcoe

        # If you need Country copied from a specific dataset
        if "Country" in self.wind_lcoe:
            best["Country"] = self.wind_lcoe["Country"]

        calculate_shares(best, "Cheapest_Technology")
        return best

    def concessional_model_pipeline(self):

        def process_result(data, benchmark, technology):
            if technology in ["Wind", "Solar"]:
                technology_type = "VRE"
            else:
                technology_type = "Firm"
            data = self.abatement_class.calculate_abatement_potential(data, technology_type=technology_type)
            data = self.calculate_abatement_costs(data=data, benchmark=benchmark, technology=technology)
            return data


        # Set benchmark
        #benchmark=[30, 40, 50, 60, 70]
        benchmark = [50]

        # Calculate LCOE using predicted WACCs and regional costs, alongside a uniform calculation
        self.solar_lcoe = self.calculate_lcoe_v4(self.solar_processed, technology="Solar")
        self.wind_lcoe = self.calculate_lcoe_v4(self.wind_onshore, technology="Onshore Wind")
        self.offshore_lcoe = self.calculate_lcoe_v4(self.wind_offshore, technology="Offshore Wind")

        # Calculate LCOE for other renewables
        self.hydro_lcoe, self.geothermal_lcoe, self.bioenergy_lcoe = self.calculate_other_renewables()

        # Initialise PostProcessor object
        self.postprocessor = PostProcessor(output_folder, self.solar_lcoe, self.wind_lcoe, self.offshore_lcoe, self.GDP_data, self.land_cover, self.land_mapping, self.country_grids, self.country_mapping, self.solar_cf, self.wind_cf, self.country_wacc_mapping)
        
        # Initialise abatement class
        self.abatement_class = AbatementEstimator(wind_results=self.wind_lcoe, solar_results=self.solar_lcoe,
                                                  carbon_intensity=self.carbon_intensity, geodata_class=self.geodata,
                                                  postprocessor=self.postprocessor, ember_data=self.ember_data,
                                                  IFI_data="./DATA/IFI Grid Factors.csv",
                                                  GEM_data="./DATA/Global-Integrated-Power-February-2026.csv")
        self.solar_lcoe, self.wind_lcoe = self.abatement_class.abatement_model_pipeline()
        # Calculate for all
        self.solar_lcoe = process_result(self.solar_lcoe, benchmark=benchmark, technology="Solar")
        self.wind_lcoe = process_result(self.wind_lcoe, benchmark=benchmark, technology="Wind")
        self.geothermal_lcoe = process_result(self.geothermal_lcoe, benchmark=benchmark, technology="Geothermal")
        self.hydro_lcoe = process_result(self.hydro_lcoe, benchmark=benchmark, technology="Hydro")
        self.bioenergy_lcoe = process_result(self.bioenergy_lcoe, benchmark=benchmark, technology="Bioenergy")
        cheapest_technology = self.calculate_cheapest_technology_v2()

        # Save results
        filenames=["Geothermal", "Hydro", "Bioenergy", "Wind", "Solar", "Full_Cheapest"]
        for i, results in enumerate([self.geothermal_lcoe, self.hydro_lcoe, self.bioenergy_lcoe, self.wind_lcoe, self.solar_lcoe, cheapest_technology]):
            name = filenames[i]
            results.to_netcdf("./RESULTS/FullResults_" + name + ".nc")
        
        
        
        



# Set out the Folder Paths
start_time = time.time()
data_path = "/Users/lukehatton/Documents/Imperial PhD/Analysis/LCOE Concessional Model/DATA/"
output_folder = "/Users/lukehatton/Documents/Imperial PhD/Analysis/LCOE Concessional Model/OUTPUT_FOLDER_REAL_INPUT/"

# Call the WACC Estimator function
lcoe_model = LCOEEstimator(data_path=data_path, country_grids="country_grids.nc", electricity_prices="CountryElecPrices.csv", solar_results="SOLAR_CF_MEAN.2022.nc",
                           wind_results="WIND_CF_MEAN.2022.nc", capex_mapping="IRENA_Country_Costs_2024.csv", generation_data="Ember Yearly Data 2026.csv",
                           country_codes="CountryCoding.csv", country_mapping="country_mapping.csv", economic_parameters="economic_parameters.csv",
                           output_folder=output_folder, land_cover="GlobalLandCover.nc", land_mapping="LandUseCSV.csv",
                           GDP="IMFGDPPerCapita.csv", solar_cf="SOLAR_CF_MEAN.2022.nc",
                           wind_cf="WIND_CF_MEAN.2022.nc", country_waccs_2024="fincore_country_waccs_2026_world.csv",
                           carbon_intensity="./DATA/Ember Yearly Data 2026.csv", IMF_inflation="IMF_Inflation_Wide.csv",
                           IMF_currency="IMF_Exchange_Rate_Long.csv")
lcoe_model.concessional_model_pipeline()

# Extract solar and wind results
solar_results = lcoe_model.calculate_abatement_costs(data=lcoe_model.solar_lcoe)
wind_results = lcoe_model.calculate_abatement_costs(data=lcoe_model.wind_lcoe)

# Call postprocessor to create visualisations
lcoe_model.postprocessor.visualiser_pipeline()


# Print duration
end_time = time.time()
total_time = end_time - start_time
print(f"LCOE Model took {total_time} seconds to run")
    
                                
    

